services:
    postgres:
        image: postgres:10
        container_name: postgres
        hostname: postgres
        volumes:
            - '/var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock'
            - 'dbdata:/var/lib/postgresql/data'
        env_file:
            - .env
        ports:
            - "5432:5432"
    totoro:
        build: .
        image: totoro
        container_name: totoro
        hostname: totoro
        ports:
            - '80:8000'
        env_file:
            - .env
        depends_on:
            - postgres
            - redis
        command: gunicorn --bind :8000 totoro.wsgi:application

    celery_worker:
        command: "celery -A totoro worker -l info"
        container_name: celery_worker
        depends_on:
            - totoro
            - postgres
            - redis
        image: totoro
        hostname: celery_worker
        restart: on-failure


    celery_beat:
        command: "celery -A totoro beat -l info"
        container_name: celery_beat
        depends_on:
            - totoro
            - postgres
            - redis
        image: totoro
        hostname: celery_beat
        restart: on-failure

    redis:
        image: redis:latest
        container_name: redis
        volumes:
            - "redis:/data"
        ports:
            - "6379:6379"

volumes:
    dbdata:
    redis: {}
